id = "fastapi-snippets"
name = "Fastapi Snippets"
version = "0.1.0"
schema_version = 1
authors = ["RajaSunrise <indra020204@gmail.com>"]
description = "Fastapi snippets for Zed IDE."
repository = "https://github.com/NarmadaWeb/fastapi-snippets-zed"

snippets = "./snippets/python.json"
